//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEVELOP_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrito
    {
        public int Id { get; set; }
        public Nullable<int> Id_Producto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> CostoTotal { get; set; }
        
        public virtual Producto Producto { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public byte[] Imagen { get; set; }
        public string Descripcion { get; set; }
    }
}
